# tell docker what version of the docker-compose.yml we're using
version: '3'

# define the network
networks:
  web-network:

# start the services section
services:
  docker-php-fpm:
    # define the directory where the build should happened,
    # i.e. where the Dockerfile of the service is located
    # all paths are relative to the location of docker-compose.yml
    build:
      context: ./docker/php-fpm
    # reserve a tty - otherwise the container shuts down immediately
    # corresponds to the "-i" flag
    tty: true
    # mount the project directory (project-directory) of the host to /var/www/project-directory in the container
    # corresponds to the "-v" option
    volumes:
      - .:/var/www/craft-site
    # attach container to network
    networks:
      - web-network

  docker-nginx:
    build:
      context: ./docker/nginx
    # defines the port mapping
    # corresponds to the "-p" flag
    ports:
      - "8080:80"
    tty: true
    volumes:
      - ./web:/var/www/craft-site/web
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    networks:
      - web-network

  docker-postgres:
    build:
      context: ./docker/postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
      POSTGRES_DB: craft_site
    networks:
      - web-network
